#!/usr/bin/env ruby

require_relative 'lib/strongstart_release/version'

gemfile = "strongstart_release-#{StrongstartRelease::VERSION}.gem"
puts "Building #{gemfile}"
build_cmd = "gem build"

unless system(build_cmd)
    puts "Failed to build gem. Fatal."
    exit 1
end

puts "Publishing #{gemfile} to GitHub Packages"
publish_cmd = "gem push --key github --host https://rubygems.pkg.github.com/strong-start #{gemfile}"
if system(publish_cmd)
    puts "Successfully published #{gemfile} to GitHub Packages."
else
    puts "Failed to push gem to GitHub Packages."
    exit 1
end

# gem push --key github --host https://rubygems.pkg.github.com/strongstart strongstart_release-0.1.0.gem